- name: ensure backup directory exists on target
  ansible.builtin.file:
    path: "{{ var_backup_dir }}" 
    owner: root
    group: root
    mode: 0750
    state: directory
  tags:
  - backup

- name: ensure backup and restore scripts exist on target
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ var_backup_dir }}/{{ item }}"
    mode: 0750
    owner: root
    group: root
  register: backup_scripts
  with_items:
    - netbox-backup
    - netbox-restore.bash
  tags:
  - backup

- name: execute a backup job if the script is new on target or it has recently changed
  shell: "{{ var_backup_dir }}/netbox-backup"
  when: backup_scripts.changed
  tags:
  - backup

- name: ensure a cron runs backup script daily 
  ansible.builtin.copy:
    src: netbox-backup
    dest: /etc/cron.daily/netbox-backup 
    owner: root
    group: root
    mode: 0700
  tags:
  - backup
