---
dependency:
   name: galaxy
driver:
   name: ec2
platforms:
  - name: instance
    image_owner: "099720109477"
    image_name: ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd-server-*
    instance_type: t3.micro
    vpc_subnet_id: scrubbed
    tags:
      Name: molecule_instance
provisioner:
  name: ansible
verifier:
  name: ansible
